// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToProxies = new Map<string, string>();
contractsToProxies.set(
  '0x7935a51addab8550d346feef34e02f67c9330109', // AggregatorBNB
  '0xb6064ed41d4f67e353768aa239ca86f4f73665a1'
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
