// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToProxies = new Map<string, string>();
contractsToProxies.set(
  '0x137924d7c36816e0dcaf016eb617cc2c92c05782', // AggregatorBNB
  '0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE'
);
contractsToProxies.set(
  '0x8d9a3c662f5cad6f0221a0c1760875350bb1c279', // AggregatorHZN
  '0x5cdC928307CeEe1d2DE35fe61e86b5ff438D43d3'
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
